---
sudo: required
language: python
python:
  - "3.8"
services: docker

cache:
  - pip

install:
  - pip install --upgrade pip
  - pip install pipenv
  - pipenv --bare install -d --deploy

script:
  - ansible-lint roles/*
  - yamllint roles/*
  # - 'distribution=${distribution} molecule lint'
  # from: https://github.com/diodonfrost/ansible-role-vagrant/blob/3ecbde5ef63fce6cc7bff7fd625af0461a88a7f0/.travis.yml#L162
  - 'distribution=${distribution} molecule test'

## modified from: https://github.com/diodonfrost/ansible-role-vagrant/blob/3ecbde5ef63fce6cc7bff7fd625af0461a88a7f0/.travis.yml
env:
#-----------------------------------------------
#
# CentOS
#
#-----------------------------------------------
  - distribution: centos-8
  - distribution: centos-7
  - distribution: centos-6

#--------------------------------
#
# Fedora
#
#--------------------------------
  - distribution: fedora-33
  - distribution: fedora-32
  - distribution: fedora-31
  - distribution: fedora-30
  - distribution: fedora-29
  - distribution: fedora-28
  - distribution: fedora-27
  - distribution: fedora-26

#--------------------------------
#
# Ubuntu
#
#--------------------------------
  - distribution: ubuntu-20.04
  - distribution: ubuntu-18.04
  - distribution: ubuntu-16.04
  - distribution: ubuntu-14.04

#--------------------------------
#
# Debian
#
#--------------------------------
  - distribution: debian-10
  - distribution: debian-9
  - distribution: debian-8

##

# https://github.com/diodonfrost/ansible-role-vagrant/blob/3ecbde5ef63fce6cc7bff7fd625af0461a88a7f0/.travis.yml#L155-L156
before_install:
  - 'docker pull diodonfrost/${distribution}-ansible:latest'

# from: https://github.com/diodonfrost/ansible-role-vagrant/blob/3ecbde5ef63fce6cc7bff7fd625af0461a88a7f0/.travis.yml#L164-L165
notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
