---
# ansible-playbook -i localhost, playbook.yml -e 'ansible_python_interpreter=/usr/bin/python3'

- hosts: all
  connection: local
  # become: yes
  gather_facts: yes
  vars:
    libvirt_pls: true
  roles:
    - role: kvm
    - role: vmware
    - role: virtualbox
    - role: docker
    - role: podman
    - role: lxd
    - role: packer
    - role: vagrant
