---
# Install vagrant on Debian

- name: add hashicorp apt signing key
  become: true
  apt_key:
    url: 'https://apt.releases.hashicorp.com/gpg'
    state: present

- name: setup hashicorp apt repository on Ubuntu
  become: true
  apt_repository:
    repo: "deb [arch=amd64] https://apt.releases.hashicorp.com {{ ansible_facts['distribution_release'] }} main"
    state: present

- name: installing vagrant
  become: true
  package:
    name: vagrant
    state: present
