---
# tasks file for vagrant

- name: 'CentOS'
  include_tasks: install_CentOS.yml
  when: ansible_facts['distribution'] == "CentOS" and ansible_facts['distribution_version']|int <= 7

- name: 'Debian'
  include_tasks: install_Debian.yml
  when: ansible_facts['os_family'] == "Debian"

- name: 'Fedora'
  include_tasks: install_Fedora.yml
  when: ansible_facts['distribution'] == "Fedora" and ansible_facts['distribution_version']|int == 30

- name: 'RedHat'
  include_tasks: install_RedHat.yml
  when: ansible_facts['distribution'] == "RedHat" and ansible_facts['distribution_version']|int <= 8

- name: 'Install libvirt plugin'
  include_tasks: install_libvirt.yml
  when:
    - libvirt_pls is defined
    - libvirt_pls
    # only implementing in debian right now, because that is my only experience/testing systems
    - ansible_facts['os_family'] == "Debian"
