---
# Install VMware Workstation
# https://docs.vmware.com/en/VMware-Workstation-Pro/15.0/com.vmware.ws.using.doc/GUID-42F4754B-7547-4A4D-AC08-353D321A051B.html

- name: download VMware Workstation bundle
  command:
    cmd: |
      curl --fail --silent --show-error --location --compressed
      "{{ vmware_bundle_url }}"
      -H 'Accept-Language: en-US,en;q=0.5'
      -H 'Connection: keep-alive'
      -H 'User-Agent: Mozilla'
      -o /tmp/vmware-workstation.bundle
  args:
    creates: /tmp/vmware-workstation.bundle

- name: Ensure bundle is executable directory exists
  file:
    path: /tmp/vmware-workstation.bundle
    state: file
    mode: '0755'

- name: Ensure /etc/init.d directory exists
  file:
    path: /etc/init.d
    state: directory
    mode: '0755'
  become: yes

- name: install VMware Workstation
  command: /tmp/vmware-workstation.bundle --console --eulas-agreed --required
  args:
    creates: /usr/bin/vmware
  become: yes

- name: delete temporary download files
  file:
    path: /tmp/vmware-workstation.bundle
    state: absent
  when: cleanup_vmware_bundle
