---
- name: Uninstall old versions
  apt:
    name: >-
        docker, docker-engine, docker.io,
        containerd, runc
    state: absent
  become: yes
  when: not snap_version

- name: Add Docker apt signing key
  apt_key:
    url: "{{ item }}"
    state: present
  with_items:
    - https://download.docker.com/linux/ubuntu/gpg
  become: yes
  when: not snap_version

- name: Setup Docker apt repository on Ubuntu
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_facts['distribution_release'] }} stable"
    state: present
  become: yes
  when: not snap_version

- name: Install packages to allow apt to use a repository over HTTPS
  apt:
    update_cache: yes
    name: "{{ ubuntu_prereq_packages }}"
    state: present
  become: yes
  when: not snap_version

- name: Install Docker-CE
  apt:
    update_cache: yes
    name: "{{ ubuntu_docker_packages }}"
    state: present
  become: yes
  when: not snap_version

- name: Install Docker snap version
  snap:
    name: docker
  become: yes
  when: snap_version
