---
# tasks file for docker

- name: 'CentOS'
  include_tasks: install_CentOS.yml
  when: ansible_facts['distribution'] == "CentOS" and ansible_facts['distribution_version']|int <= 7

- name: 'Debian'
  include_tasks: install_Debian.yml
  when: ansible_facts['os_family'] == "Debian"

- name: 'Fedora'
  include_tasks: install_Fedora.yml
  when: ansible_facts['distribution'] == "Fedora" and ansible_facts['distribution_version']|int == 30

- include: configure.yml
  when: ansible_facts['distribution'] != 'RedHat'
