name: Ansible Galaxy

on:
  push:
    branches:
      - main
      - master
    tags:        
      - '*'

jobs:
  deploy:
    environment: main
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Deploy the collection
      uses: artis3n/ansible_galaxy_collection@v2
      with:
        api_key: '${{ secrets.GALAXY_API_KEY }}'